### ISSUE TITLE
Dodati poene

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG26-football-3d#3]
Trenutno lopta besciljno seta terenom, ne bi bilo lose dati joj svrhu u zivotu, koliko god ona naizgled nebitna bila. Dodati neke poene za skupljanje. Druga ideja bi bila da lopta mora da izbegava prepreke i dobija poene time sto upada u golove naizmenicno.

**Comment by z0cky** [comment]
Dodat cilj igrice, izbeci prepreku i postici gol
